[2022-11-28 15:30:11 +0100] [581960] [DEBUG] Current configuration:
  config: /home/credirect/Documents/CredirectSoftware/Backend/gunicorn_conf.py
  wsgi_app: None
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 5
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/credirect/Documents/CredirectSoftware/Backend
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /home/credirect/Documents/CredirectSoftware/Backend/access_log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/credirect/Documents/CredirectSoftware/Backend/error_log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: app.app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f4c42fc3be0>
  on_reload: <function OnReload.on_reload at 0x7f4c42fc3d00>
  when_ready: <function WhenReady.when_ready at 0x7f4c42fc3e20>
  pre_fork: <function Prefork.pre_fork at 0x7f4c42fc3f40>
  post_fork: <function Postfork.post_fork at 0x7f4c42fe80d0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f4c42fe81f0>
  worker_int: <function WorkerInt.worker_int at 0x7f4c42fe8310>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f4c42fe8430>
  pre_exec: <function PreExec.pre_exec at 0x7f4c42fe8550>
  pre_request: <function PreRequest.pre_request at 0x7f4c42fe8670>
  post_request: <function PostRequest.post_request at 0x7f4c42fe8700>
  child_exit: <function ChildExit.child_exit at 0x7f4c42fe8820>
  worker_exit: <function WorkerExit.worker_exit at 0x7f4c42fe8940>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f4c42fe8a60>
  on_exit: <function OnExit.on_exit at 0x7f4c42fe8b80>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2022-11-28 15:30:11 +0100] [581960] [INFO] Starting gunicorn 20.1.0
[2022-11-28 15:30:11 +0100] [581960] [DEBUG] Arbiter booted
[2022-11-28 15:30:11 +0100] [581960] [INFO] Listening at: http://0.0.0.0:8000 (581960)
[2022-11-28 15:30:11 +0100] [581960] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-28 15:30:11 +0100] [581962] [INFO] Booting worker with pid: 581962
[2022-11-28 15:30:11 +0100] [581963] [INFO] Booting worker with pid: 581963
[2022-11-28 15:30:11 +0100] [581964] [INFO] Booting worker with pid: 581964
[2022-11-28 15:30:11 +0100] [581965] [INFO] Booting worker with pid: 581965
[2022-11-28 15:30:11 +0100] [581966] [INFO] Booting worker with pid: 581966
[2022-11-28 15:30:11 +0100] [581960] [DEBUG] 5 workers
[2022-11-28 15:30:12 +0100] [581962] [INFO] Started server process [581962]
[2022-11-28 15:30:12 +0100] [581962] [INFO] Waiting for application startup.
[2022-11-28 15:30:12 +0100] [581965] [INFO] Started server process [581965]
[2022-11-28 15:30:12 +0100] [581965] [INFO] Waiting for application startup.
[2022-11-28 15:30:12 +0100] [581963] [INFO] Started server process [581963]
[2022-11-28 15:30:12 +0100] [581963] [INFO] Waiting for application startup.
[2022-11-28 15:30:12 +0100] [581964] [INFO] Started server process [581964]
[2022-11-28 15:30:12 +0100] [581964] [INFO] Waiting for application startup.
[2022-11-28 15:30:12 +0100] [581966] [INFO] Started server process [581966]
[2022-11-28 15:30:12 +0100] [581966] [INFO] Waiting for application startup.
[2022-11-28 15:30:13 +0100] [581960] [INFO] Handling signal: term
[2022-11-28 15:30:14 +0100] [581966] [INFO] Application startup complete.
[2022-11-28 15:30:14 +0100] [581966] [ERROR] Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 648, in lifespan
    await receive()
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

[2022-11-28 15:30:14 +0100] [581966] [INFO] Worker exiting (pid: 581966)
[2022-11-28 15:30:14 +0100] [581965] [INFO] Application startup complete.
[2022-11-28 15:30:14 +0100] [581965] [ERROR] Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 648, in lifespan
    await receive()
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

[2022-11-28 15:30:14 +0100] [581965] [INFO] Worker exiting (pid: 581965)
[2022-11-28 15:30:14 +0100] [581962] [INFO] Application startup complete.
[2022-11-28 15:30:14 +0100] [581962] [ERROR] Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 648, in lifespan
    await receive()
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

[2022-11-28 15:30:14 +0100] [581962] [INFO] Worker exiting (pid: 581962)
[2022-11-28 15:30:14 +0100] [581963] [INFO] Application startup complete.
[2022-11-28 15:30:14 +0100] [581963] [ERROR] Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 648, in lifespan
    await receive()
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

[2022-11-28 15:30:14 +0100] [581963] [INFO] Worker exiting (pid: 581963)
[2022-11-28 15:30:14 +0100] [581964] [INFO] Application startup complete.
[2022-11-28 15:30:14 +0100] [581964] [ERROR] Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 648, in lifespan
    await receive()
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

[2022-11-28 15:30:14 +0100] [581964] [INFO] Worker exiting (pid: 581964)
[2022-11-28 15:30:15 +0100] [581960] [INFO] Shutting down: Master
[2022-11-28 15:30:17 +0100] [582050] [DEBUG] Current configuration:
  config: /home/credirect/Documents/CredirectSoftware/Backend/gunicorn_conf.py
  wsgi_app: None
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 5
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/credirect/Documents/CredirectSoftware/Backend
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /home/credirect/Documents/CredirectSoftware/Backend/access_log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/credirect/Documents/CredirectSoftware/Backend/error_log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: app.app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7fc3c9b43be0>
  on_reload: <function OnReload.on_reload at 0x7fc3c9b43d00>
  when_ready: <function WhenReady.when_ready at 0x7fc3c9b43e20>
  pre_fork: <function Prefork.pre_fork at 0x7fc3c9b43f40>
  post_fork: <function Postfork.post_fork at 0x7fc3c9b680d0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7fc3c9b681f0>
  worker_int: <function WorkerInt.worker_int at 0x7fc3c9b68310>
  worker_abort: <function WorkerAbort.worker_abort at 0x7fc3c9b68430>
  pre_exec: <function PreExec.pre_exec at 0x7fc3c9b68550>
  pre_request: <function PreRequest.pre_request at 0x7fc3c9b68670>
  post_request: <function PostRequest.post_request at 0x7fc3c9b68700>
  child_exit: <function ChildExit.child_exit at 0x7fc3c9b68820>
  worker_exit: <function WorkerExit.worker_exit at 0x7fc3c9b68940>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7fc3c9b68a60>
  on_exit: <function OnExit.on_exit at 0x7fc3c9b68b80>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2022-11-28 15:30:17 +0100] [582050] [INFO] Starting gunicorn 20.1.0
[2022-11-28 15:30:17 +0100] [582050] [DEBUG] Arbiter booted
[2022-11-28 15:30:17 +0100] [582050] [INFO] Listening at: http://0.0.0.0:8000 (582050)
[2022-11-28 15:30:17 +0100] [582050] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-28 15:30:17 +0100] [582053] [INFO] Booting worker with pid: 582053
[2022-11-28 15:30:17 +0100] [582054] [INFO] Booting worker with pid: 582054
[2022-11-28 15:30:17 +0100] [582055] [INFO] Booting worker with pid: 582055
[2022-11-28 15:30:17 +0100] [582056] [INFO] Booting worker with pid: 582056
[2022-11-28 15:30:17 +0100] [582057] [INFO] Booting worker with pid: 582057
[2022-11-28 15:30:17 +0100] [582050] [DEBUG] 5 workers
[2022-11-28 15:30:17 +0100] [582053] [INFO] Started server process [582053]
[2022-11-28 15:30:17 +0100] [582053] [INFO] Waiting for application startup.
[2022-11-28 15:30:17 +0100] [582055] [INFO] Started server process [582055]
[2022-11-28 15:30:17 +0100] [582055] [INFO] Waiting for application startup.
[2022-11-28 15:30:18 +0100] [582054] [INFO] Started server process [582054]
[2022-11-28 15:30:18 +0100] [582054] [INFO] Waiting for application startup.
[2022-11-28 15:30:18 +0100] [582056] [INFO] Started server process [582056]
[2022-11-28 15:30:18 +0100] [582056] [INFO] Waiting for application startup.
[2022-11-28 15:30:18 +0100] [582057] [INFO] Started server process [582057]
[2022-11-28 15:30:18 +0100] [582057] [INFO] Waiting for application startup.
[2022-11-28 15:30:19 +0100] [582055] [INFO] Application startup complete.
[2022-11-28 15:30:19 +0100] [582053] [INFO] Application startup complete.
[2022-11-28 15:30:19 +0100] [582056] [INFO] Application startup complete.
[2022-11-28 15:30:19 +0100] [582054] [INFO] Application startup complete.
[2022-11-28 15:30:19 +0100] [582057] [INFO] Application startup complete.
[2022-11-28 15:31:22 +0100] [582057] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/api/api_v1/handlers/credit.py", line 47, in get_dc
    return await CreditService.get_dc(request,credit_id)
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/services/credit_service.py", line 65, in get_dc
    credit = await CreditService.get_credit_by_id(credit_id)
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/services/credit_service.py", line 137, in get_credit_by_id
    credit = await Credit.find_one(Credit.credit_id == id)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/beanie/odm/queries/find.py", line 885, in __await__
    FindQueryResultType, parse_obj(self.projection_model, document)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/beanie/odm/utils/parsing.py", line 36, in parse_obj
    return model.parse_obj(data)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/beanie/odm/documents.py", line 139, in __init__
    super(Document, self).__init__(*args, **kwargs)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for Credit
titre_foncier
  field required (type=value_error.missing)
granties
  field required (type=value_error.missing)
[2022-11-28 15:31:23 +0100] [582055] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/encoders.py", line 152, in jsonable_encoder
    data = dict(obj)
TypeError: 'wrapper_descriptor' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/encoders.py", line 157, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 253, in app
    content = await serialize_response(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 150, in serialize_response
    return jsonable_encoder(response_content)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/encoders.py", line 160, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'wrapper_descriptor' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
[2022-11-28 15:46:44 +0100] [582050] [INFO] Handling signal: term
[2022-11-28 15:46:44 +0100] [582055] [INFO] Shutting down
[2022-11-28 15:46:44 +0100] [582053] [INFO] Shutting down
[2022-11-28 15:46:44 +0100] [582054] [INFO] Shutting down
[2022-11-28 15:46:44 +0100] [582056] [INFO] Shutting down
[2022-11-28 15:46:44 +0100] [582057] [INFO] Shutting down
[2022-11-28 15:46:44 +0100] [582055] [INFO] Waiting for application shutdown.
[2022-11-28 15:46:44 +0100] [582055] [INFO] Application shutdown complete.
[2022-11-28 15:46:44 +0100] [582055] [INFO] Finished server process [582055]
[2022-11-28 15:46:44 +0100] [582053] [INFO] Waiting for application shutdown.
[2022-11-28 15:46:44 +0100] [582055] [INFO] Worker exiting (pid: 582055)
[2022-11-28 15:46:44 +0100] [582053] [INFO] Application shutdown complete.
[2022-11-28 15:46:44 +0100] [582053] [INFO] Finished server process [582053]
[2022-11-28 15:46:44 +0100] [582053] [INFO] Worker exiting (pid: 582053)
[2022-11-28 15:46:44 +0100] [582054] [INFO] Waiting for application shutdown.
[2022-11-28 15:46:44 +0100] [582054] [INFO] Application shutdown complete.
[2022-11-28 15:46:44 +0100] [582054] [INFO] Finished server process [582054]
[2022-11-28 15:46:44 +0100] [582054] [INFO] Worker exiting (pid: 582054)
[2022-11-28 15:46:44 +0100] [582056] [INFO] Waiting for application shutdown.
[2022-11-28 15:46:44 +0100] [582056] [INFO] Application shutdown complete.
[2022-11-28 15:46:44 +0100] [582056] [INFO] Finished server process [582056]
[2022-11-28 15:46:44 +0100] [582056] [INFO] Worker exiting (pid: 582056)
[2022-11-28 15:46:44 +0100] [582057] [INFO] Waiting for application shutdown.
[2022-11-28 15:46:44 +0100] [582057] [INFO] Application shutdown complete.
[2022-11-28 15:46:44 +0100] [582057] [INFO] Finished server process [582057]
[2022-11-28 15:46:44 +0100] [582057] [INFO] Worker exiting (pid: 582057)
[2022-11-28 15:46:45 +0100] [582050] [INFO] Shutting down: Master
[2022-11-28 15:46:45 +0100] [582590] [DEBUG] Current configuration:
  config: /home/credirect/Documents/CredirectSoftware/Backend/gunicorn_conf.py
  wsgi_app: None
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 5
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/credirect/Documents/CredirectSoftware/Backend
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /home/credirect/Documents/CredirectSoftware/Backend/access_log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/credirect/Documents/CredirectSoftware/Backend/error_log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: app.app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f22e938bbe0>
  on_reload: <function OnReload.on_reload at 0x7f22e938bd00>
  when_ready: <function WhenReady.when_ready at 0x7f22e938be20>
  pre_fork: <function Prefork.pre_fork at 0x7f22e938bf40>
  post_fork: <function Postfork.post_fork at 0x7f22e93b00d0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f22e93b01f0>
  worker_int: <function WorkerInt.worker_int at 0x7f22e93b0310>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f22e93b0430>
  pre_exec: <function PreExec.pre_exec at 0x7f22e93b0550>
  pre_request: <function PreRequest.pre_request at 0x7f22e93b0670>
  post_request: <function PostRequest.post_request at 0x7f22e93b0700>
  child_exit: <function ChildExit.child_exit at 0x7f22e93b0820>
  worker_exit: <function WorkerExit.worker_exit at 0x7f22e93b0940>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f22e93b0a60>
  on_exit: <function OnExit.on_exit at 0x7f22e93b0b80>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2022-11-28 15:46:45 +0100] [582590] [INFO] Starting gunicorn 20.1.0
[2022-11-28 15:46:45 +0100] [582590] [DEBUG] Arbiter booted
[2022-11-28 15:46:45 +0100] [582590] [INFO] Listening at: http://0.0.0.0:8000 (582590)
[2022-11-28 15:46:45 +0100] [582590] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-28 15:46:45 +0100] [582592] [INFO] Booting worker with pid: 582592
[2022-11-28 15:46:45 +0100] [582593] [INFO] Booting worker with pid: 582593
[2022-11-28 15:46:45 +0100] [582594] [INFO] Booting worker with pid: 582594
[2022-11-28 15:46:45 +0100] [582595] [INFO] Booting worker with pid: 582595
[2022-11-28 15:46:45 +0100] [582596] [INFO] Booting worker with pid: 582596
[2022-11-28 15:46:45 +0100] [582590] [DEBUG] 5 workers
[2022-11-28 15:46:45 +0100] [582592] [INFO] Started server process [582592]
[2022-11-28 15:46:45 +0100] [582592] [INFO] Waiting for application startup.
[2022-11-28 15:46:46 +0100] [582593] [INFO] Started server process [582593]
[2022-11-28 15:46:46 +0100] [582593] [INFO] Waiting for application startup.
[2022-11-28 15:46:46 +0100] [582595] [INFO] Started server process [582595]
[2022-11-28 15:46:46 +0100] [582595] [INFO] Waiting for application startup.
[2022-11-28 15:46:46 +0100] [582594] [INFO] Started server process [582594]
[2022-11-28 15:46:46 +0100] [582594] [INFO] Waiting for application startup.
[2022-11-28 15:46:46 +0100] [582596] [INFO] Started server process [582596]
[2022-11-28 15:46:46 +0100] [582596] [INFO] Waiting for application startup.
[2022-11-28 15:46:48 +0100] [582593] [INFO] Application startup complete.
[2022-11-28 15:46:48 +0100] [582596] [INFO] Application startup complete.
[2022-11-28 15:46:48 +0100] [582595] [INFO] Application startup complete.
[2022-11-28 15:46:48 +0100] [582592] [INFO] Application startup complete.
[2022-11-28 15:46:48 +0100] [582594] [INFO] Application startup complete.
[2022-11-28 15:54:25 +0100] [582594] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/api/api_v1/handlers/credit.py", line 61, in delete_credit
    return await CreditService.delete_credit(credit_id)
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/services/credit_service.py", line 95, in delete_credit
    credit = await Credit.find_one(Credit.credit_id == id)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/beanie/odm/queries/find.py", line 885, in __await__
    FindQueryResultType, parse_obj(self.projection_model, document)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/beanie/odm/utils/parsing.py", line 36, in parse_obj
    return model.parse_obj(data)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/beanie/odm/documents.py", line 139, in __init__
    super(Document, self).__init__(*args, **kwargs)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for Credit
titre_foncier
  field required (type=value_error.missing)
garanties
  field required (type=value_error.missing)
[2022-11-28 16:12:27 +0100] [582593] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/api/api_v1/handlers/credit.py", line 47, in get_dc
    return await CreditService.get_dc(request,credit_id)
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/services/credit_service.py", line 68, in get_dc
    return templates.TemplateResponse("dc.html", context)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/templating.py", line 97, in TemplateResponse
    template = self.get_template(name)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/templating.py", line 84, in get_template
    return self.env.get_template(name)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "app/static/dc.html", line 200, in template
    {{prospect.engagements_bancaires.map(eng_ban)=>}}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '='
[2022-11-28 16:12:27 +0100] [582592] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/encoders.py", line 152, in jsonable_encoder
    data = dict(obj)
TypeError: 'wrapper_descriptor' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/encoders.py", line 157, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 253, in app
    content = await serialize_response(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 150, in serialize_response
    return jsonable_encoder(response_content)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/encoders.py", line 160, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'wrapper_descriptor' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
[2022-11-28 16:15:25 +0100] [582593] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/api/api_v1/handlers/credit.py", line 47, in get_dc
    return await CreditService.get_dc(request,credit_id)
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/services/credit_service.py", line 68, in get_dc
    return templates.TemplateResponse("dc.html", context)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/templating.py", line 97, in TemplateResponse
    template = self.get_template(name)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/templating.py", line 84, in get_template
    return self.env.get_template(name)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "app/static/dc.html", line 200, in template
    {{prospect.engagements_bancaires.map(eng_ban)=>}}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '='
[2022-11-28 16:15:33 +0100] [582592] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/api/api_v1/handlers/credit.py", line 47, in get_dc
    return await CreditService.get_dc(request,credit_id)
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/services/credit_service.py", line 68, in get_dc
    return templates.TemplateResponse("dc.html", context)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/templating.py", line 97, in TemplateResponse
    template = self.get_template(name)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/templating.py", line 84, in get_template
    return self.env.get_template(name)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "app/static/dc.html", line 200, in template
    {{prospect.engagements_bancaires.map(eng_ban)=>}}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '='
[2022-11-28 16:17:43 +0100] [582593] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/api/api_v1/handlers/credit.py", line 47, in get_dc
    return await CreditService.get_dc(request,credit_id)
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/services/credit_service.py", line 68, in get_dc
    return templates.TemplateResponse("dc.html", context)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/templating.py", line 97, in TemplateResponse
    template = self.get_template(name)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/templating.py", line 84, in get_template
    return self.env.get_template(name)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "app/static/dc.html", line 200, in template
    {{prospect.engagements_bancaires.map(eng_ban=>(}}
jinja2.exceptions.TemplateSyntaxError: unexpected '>'
[2022-11-28 16:17:45 +0100] [582594] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/api/api_v1/handlers/credit.py", line 47, in get_dc
    return await CreditService.get_dc(request,credit_id)
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/services/credit_service.py", line 68, in get_dc
    return templates.TemplateResponse("dc.html", context)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/templating.py", line 97, in TemplateResponse
    template = self.get_template(name)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/templating.py", line 84, in get_template
    return self.env.get_template(name)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "app/static/dc.html", line 200, in template
    {{prospect.engagements_bancaires.map(eng_ban=>(}}
jinja2.exceptions.TemplateSyntaxError: unexpected '>'
[2022-11-28 16:18:17 +0100] [582594] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/api/api_v1/handlers/credit.py", line 47, in get_dc
    return await CreditService.get_dc(request,credit_id)
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/services/credit_service.py", line 68, in get_dc
    return templates.TemplateResponse("dc.html", context)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/templating.py", line 97, in TemplateResponse
    template = self.get_template(name)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/templating.py", line 84, in get_template
    return self.env.get_template(name)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "app/static/dc.html", line 200, in template
    {{prospect.engagements_bancaires.map(eng_ban => (}}
jinja2.exceptions.TemplateSyntaxError: unexpected '>'
[2022-11-28 16:25:31 +0100] [582596] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/api/api_v1/handlers/credit.py", line 47, in get_dc
    return await CreditService.get_dc(request,credit_id)
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/services/credit_service.py", line 68, in get_dc
    return templates.TemplateResponse("dc.html", context)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/templating.py", line 97, in TemplateResponse
    template = self.get_template(name)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/templating.py", line 84, in get_template
    return self.env.get_template(name)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "app/static/dc.html", line 200, in template
    {% prospect.engagements_bancaires.map(eng_ban => ( %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'prospect'.
[2022-11-28 16:27:10 +0100] [582595] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/api/api_v1/handlers/credit.py", line 47, in get_dc
    return await CreditService.get_dc(request,credit_id)
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/services/credit_service.py", line 68, in get_dc
    return templates.TemplateResponse("dc.html", context)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/templating.py", line 97, in TemplateResponse
    template = self.get_template(name)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/templating.py", line 84, in get_template
    return self.env.get_template(name)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "app/static/dc.html", line 202, in template
    <td>{{eng_ban.nom  eng_ban.prenom}}</td>
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'eng_ban'
[2022-11-28 16:27:11 +0100] [582594] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/api/api_v1/handlers/credit.py", line 47, in get_dc
    return await CreditService.get_dc(request,credit_id)
  File "/home/credirect/Documents/CredirectSoftware/Backend/app/services/credit_service.py", line 68, in get_dc
    return templates.TemplateResponse("dc.html", context)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/templating.py", line 97, in TemplateResponse
    template = self.get_template(name)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/starlette/templating.py", line 84, in get_template
    return self.env.get_template(name)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/credirect/Documents/CredirectSoftware/Backend/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "app/static/dc.html", line 202, in template
    <td>{{eng_ban.nom  eng_ban.prenom}}</td>
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'eng_ban'
[2022-11-29 15:44:25 +0100] [582590] [INFO] Handling signal: term
[2022-11-29 15:44:25 +0100] [582595] [INFO] Shutting down
[2022-11-29 15:44:25 +0100] [582596] [INFO] Shutting down
[2022-11-29 15:44:25 +0100] [582594] [INFO] Shutting down
[2022-11-29 15:44:25 +0100] [582592] [INFO] Shutting down
[2022-11-29 15:44:25 +0100] [582593] [INFO] Shutting down
[2022-11-29 15:44:25 +0100] [582595] [INFO] Waiting for application shutdown.
[2022-11-29 15:44:25 +0100] [582595] [INFO] Application shutdown complete.
[2022-11-29 15:44:25 +0100] [582595] [INFO] Finished server process [582595]
[2022-11-29 15:44:25 +0100] [582595] [INFO] Worker exiting (pid: 582595)
[2022-11-29 15:44:25 +0100] [582596] [INFO] Waiting for application shutdown.
[2022-11-29 15:44:25 +0100] [582596] [INFO] Application shutdown complete.
[2022-11-29 15:44:25 +0100] [582596] [INFO] Finished server process [582596]
[2022-11-29 15:44:25 +0100] [582596] [INFO] Worker exiting (pid: 582596)
[2022-11-29 15:44:25 +0100] [582594] [INFO] Waiting for application shutdown.
[2022-11-29 15:44:25 +0100] [582594] [INFO] Application shutdown complete.
[2022-11-29 15:44:25 +0100] [582594] [INFO] Finished server process [582594]
[2022-11-29 15:44:25 +0100] [582592] [INFO] Waiting for application shutdown.
[2022-11-29 15:44:25 +0100] [582592] [INFO] Application shutdown complete.
[2022-11-29 15:44:25 +0100] [582592] [INFO] Finished server process [582592]
[2022-11-29 15:44:25 +0100] [582594] [INFO] Worker exiting (pid: 582594)
[2022-11-29 15:44:25 +0100] [582592] [INFO] Worker exiting (pid: 582592)
[2022-11-29 15:44:25 +0100] [582593] [INFO] Waiting for application shutdown.
[2022-11-29 15:44:25 +0100] [582593] [INFO] Application shutdown complete.
[2022-11-29 15:44:25 +0100] [582593] [INFO] Finished server process [582593]
[2022-11-29 15:44:25 +0100] [582593] [INFO] Worker exiting (pid: 582593)
[2022-11-29 15:44:26 +0100] [582590] [INFO] Shutting down: Master
[2022-11-29 15:44:26 +0100] [600073] [DEBUG] Current configuration:
  config: /home/credirect/Documents/CredirectSoftware/Backend/gunicorn_conf.py
  wsgi_app: None
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 5
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/credirect/Documents/CredirectSoftware/Backend
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /home/credirect/Documents/CredirectSoftware/Backend/access_log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/credirect/Documents/CredirectSoftware/Backend/error_log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: app.app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f31829cbbe0>
  on_reload: <function OnReload.on_reload at 0x7f31829cbd00>
  when_ready: <function WhenReady.when_ready at 0x7f31829cbe20>
  pre_fork: <function Prefork.pre_fork at 0x7f31829cbf40>
  post_fork: <function Postfork.post_fork at 0x7f31829f00d0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f31829f01f0>
  worker_int: <function WorkerInt.worker_int at 0x7f31829f0310>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f31829f0430>
  pre_exec: <function PreExec.pre_exec at 0x7f31829f0550>
  pre_request: <function PreRequest.pre_request at 0x7f31829f0670>
  post_request: <function PostRequest.post_request at 0x7f31829f0700>
  child_exit: <function ChildExit.child_exit at 0x7f31829f0820>
  worker_exit: <function WorkerExit.worker_exit at 0x7f31829f0940>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f31829f0a60>
  on_exit: <function OnExit.on_exit at 0x7f31829f0b80>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2022-11-29 15:44:26 +0100] [600073] [INFO] Starting gunicorn 20.1.0
[2022-11-29 15:44:26 +0100] [600073] [DEBUG] Arbiter booted
[2022-11-29 15:44:26 +0100] [600073] [INFO] Listening at: http://0.0.0.0:8000 (600073)
[2022-11-29 15:44:26 +0100] [600073] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-29 15:44:26 +0100] [600075] [INFO] Booting worker with pid: 600075
[2022-11-29 15:44:26 +0100] [600076] [INFO] Booting worker with pid: 600076
[2022-11-29 15:44:26 +0100] [600077] [INFO] Booting worker with pid: 600077
[2022-11-29 15:44:26 +0100] [600078] [INFO] Booting worker with pid: 600078
[2022-11-29 15:44:26 +0100] [600073] [DEBUG] 5 workers
[2022-11-29 15:44:26 +0100] [600079] [INFO] Booting worker with pid: 600079
[2022-11-29 15:44:27 +0100] [600075] [INFO] Started server process [600075]
[2022-11-29 15:44:27 +0100] [600075] [INFO] Waiting for application startup.
[2022-11-29 15:44:27 +0100] [600076] [INFO] Started server process [600076]
[2022-11-29 15:44:27 +0100] [600076] [INFO] Waiting for application startup.
[2022-11-29 15:44:27 +0100] [600077] [INFO] Started server process [600077]
[2022-11-29 15:44:27 +0100] [600077] [INFO] Waiting for application startup.
[2022-11-29 15:44:27 +0100] [600079] [INFO] Started server process [600079]
[2022-11-29 15:44:27 +0100] [600079] [INFO] Waiting for application startup.
[2022-11-29 15:44:27 +0100] [600078] [INFO] Started server process [600078]
[2022-11-29 15:44:27 +0100] [600078] [INFO] Waiting for application startup.
[2022-11-29 15:44:28 +0100] [600077] [INFO] Application startup complete.
[2022-11-29 15:44:28 +0100] [600079] [INFO] Application startup complete.
[2022-11-29 15:44:28 +0100] [600075] [INFO] Application startup complete.
[2022-11-29 15:44:28 +0100] [600076] [INFO] Application startup complete.
[2022-11-29 15:44:28 +0100] [600078] [INFO] Application startup complete.
[2022-11-29 15:54:42 +0100] [600073] [INFO] Handling signal: term
[2022-11-29 15:54:42 +0100] [600078] [INFO] Shutting down
[2022-11-29 15:54:42 +0100] [600076] [INFO] Shutting down
[2022-11-29 15:54:42 +0100] [600079] [INFO] Shutting down
[2022-11-29 15:54:42 +0100] [600077] [INFO] Shutting down
[2022-11-29 15:54:42 +0100] [600075] [INFO] Shutting down
[2022-11-29 15:54:42 +0100] [600078] [INFO] Waiting for application shutdown.
[2022-11-29 15:54:42 +0100] [600078] [INFO] Application shutdown complete.
[2022-11-29 15:54:42 +0100] [600078] [INFO] Finished server process [600078]
[2022-11-29 15:54:42 +0100] [600078] [INFO] Worker exiting (pid: 600078)
[2022-11-29 15:54:42 +0100] [600076] [INFO] Waiting for application shutdown.
[2022-11-29 15:54:42 +0100] [600076] [INFO] Application shutdown complete.
[2022-11-29 15:54:42 +0100] [600076] [INFO] Finished server process [600076]
[2022-11-29 15:54:42 +0100] [600076] [INFO] Worker exiting (pid: 600076)
[2022-11-29 15:54:42 +0100] [600079] [INFO] Waiting for application shutdown.
[2022-11-29 15:54:42 +0100] [600079] [INFO] Application shutdown complete.
[2022-11-29 15:54:42 +0100] [600079] [INFO] Finished server process [600079]
[2022-11-29 15:54:42 +0100] [600079] [INFO] Worker exiting (pid: 600079)
[2022-11-29 15:54:42 +0100] [600077] [INFO] Waiting for application shutdown.
[2022-11-29 15:54:42 +0100] [600077] [INFO] Application shutdown complete.
[2022-11-29 15:54:42 +0100] [600077] [INFO] Finished server process [600077]
[2022-11-29 15:54:42 +0100] [600077] [INFO] Worker exiting (pid: 600077)
[2022-11-29 15:54:42 +0100] [600075] [INFO] Waiting for application shutdown.
[2022-11-29 15:54:42 +0100] [600075] [INFO] Application shutdown complete.
[2022-11-29 15:54:42 +0100] [600075] [INFO] Finished server process [600075]
[2022-11-29 15:54:42 +0100] [600075] [INFO] Worker exiting (pid: 600075)
[2022-11-29 15:54:42 +0100] [600073] [INFO] Shutting down: Master
[2022-11-29 15:54:43 +0100] [600612] [DEBUG] Current configuration:
  config: /home/credirect/Documents/CredirectSoftware/Backend/gunicorn_conf.py
  wsgi_app: None
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 5
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/credirect/Documents/CredirectSoftware/Backend
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /home/credirect/Documents/CredirectSoftware/Backend/access_log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/credirect/Documents/CredirectSoftware/Backend/error_log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: app.app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7feb3fc53be0>
  on_reload: <function OnReload.on_reload at 0x7feb3fc53d00>
  when_ready: <function WhenReady.when_ready at 0x7feb3fc53e20>
  pre_fork: <function Prefork.pre_fork at 0x7feb3fc53f40>
  post_fork: <function Postfork.post_fork at 0x7feb3fc780d0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7feb3fc781f0>
  worker_int: <function WorkerInt.worker_int at 0x7feb3fc78310>
  worker_abort: <function WorkerAbort.worker_abort at 0x7feb3fc78430>
  pre_exec: <function PreExec.pre_exec at 0x7feb3fc78550>
  pre_request: <function PreRequest.pre_request at 0x7feb3fc78670>
  post_request: <function PostRequest.post_request at 0x7feb3fc78700>
  child_exit: <function ChildExit.child_exit at 0x7feb3fc78820>
  worker_exit: <function WorkerExit.worker_exit at 0x7feb3fc78940>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7feb3fc78a60>
  on_exit: <function OnExit.on_exit at 0x7feb3fc78b80>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2022-11-29 15:54:43 +0100] [600612] [INFO] Starting gunicorn 20.1.0
[2022-11-29 15:54:43 +0100] [600612] [DEBUG] Arbiter booted
[2022-11-29 15:54:43 +0100] [600612] [INFO] Listening at: http://0.0.0.0:8000 (600612)
[2022-11-29 15:54:43 +0100] [600612] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-11-29 15:54:43 +0100] [600614] [INFO] Booting worker with pid: 600614
[2022-11-29 15:54:43 +0100] [600615] [INFO] Booting worker with pid: 600615
[2022-11-29 15:54:43 +0100] [600616] [INFO] Booting worker with pid: 600616
[2022-11-29 15:54:43 +0100] [600617] [INFO] Booting worker with pid: 600617
[2022-11-29 15:54:43 +0100] [600618] [INFO] Booting worker with pid: 600618
[2022-11-29 15:54:43 +0100] [600612] [DEBUG] 5 workers
[2022-11-29 15:54:43 +0100] [600615] [INFO] Started server process [600615]
[2022-11-29 15:54:43 +0100] [600615] [INFO] Waiting for application startup.
[2022-11-29 15:54:43 +0100] [600614] [INFO] Started server process [600614]
[2022-11-29 15:54:43 +0100] [600614] [INFO] Waiting for application startup.
[2022-11-29 15:54:43 +0100] [600616] [INFO] Started server process [600616]
[2022-11-29 15:54:43 +0100] [600616] [INFO] Waiting for application startup.
[2022-11-29 15:54:43 +0100] [600617] [INFO] Started server process [600617]
[2022-11-29 15:54:43 +0100] [600617] [INFO] Waiting for application startup.
[2022-11-29 15:54:44 +0100] [600618] [INFO] Started server process [600618]
[2022-11-29 15:54:44 +0100] [600618] [INFO] Waiting for application startup.
[2022-11-29 15:54:45 +0100] [600617] [INFO] Application startup complete.
[2022-11-29 15:54:45 +0100] [600614] [INFO] Application startup complete.
[2022-11-29 15:54:45 +0100] [600616] [INFO] Application startup complete.
[2022-11-29 15:54:45 +0100] [600615] [INFO] Application startup complete.
[2022-11-29 15:54:45 +0100] [600618] [INFO] Application startup complete.
